### PR TITLE
419 check schademelding schadegeval gebruik

### LINKED ISSUE #419: Check schademelding <-> schadegeval gebruik
Momenteel wordt de term schademelding gebruikt wanneer het eigenlijk over een schadegeval gaat. Er zal nagegaan moeten worden of de gebruikte schade term "juist" is of we deze aan moeten passen.

### PR DESCRIPTION
**Pull request by SanderDevisscher**
fixes #419 

Ik heb alle schademeldingen vervangen door schadegevallen. 
Je kan het testen door deze repo lokaal te syncen en dan het build docker evironment scriptje te gebruiken. Have fun ;-)

### CODE REVIEW

**Comment by mvarewyck** [comment]
@SanderDevisscher there is something weird with this branch. I couldn't see or push to it. 

I found only 1 extra occurrence of the 'schademeldingen'. Rest seems ok to me:
* R CMD check succeeded
* Able to start public & private app
* I did not check the docker image - as the code was not changed there

**Review by mvarewyck — DISMISSED** [review]

**Comment by SanderDevisscher** [comment]
When you expand the slider at Evolutie gerapporteerd afschot<sup>1</sup> to include 2023 on the wbe page I get this error:
`st_drop_geometry only works with objects of class sf`. 

The error does not occur on the PRD.
@mvarewyck Can you please fix this before merging ?

<sup>1</sup>issue is present in multiple wbe's.

**Comment by SanderDevisscher** [comment]
might be related but when I switch the landkaart slider to 2023 it crashes.

**Comment by SanderDevisscher** [comment]
I cherry picked 2 commits from the [update_august_2023](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/update_august_2023) since these are more relevant than the fixes for #407 which are more a nice to have.

**Comment by SanderDevisscher** [comment]
https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/421#issuecomment-1759647735

issue occurs in master version as well merging this branch won't create new issue but bug should be fixed before deploying to UAT/PRD.

**Comment by SanderDevisscher** [comment]
@mvarewyck @RuttenAnneleen can you check latest changes ?

**Comment by SanderDevisscher** [comment]
This works as it should but I can't merge without cheating. @RuttenAnneleen can you test, approve and merge ? 

You should be able to use docker environment script

**Pull request merged**
