### PR TITLE
Updates v0.3.4

### PR DESCRIPTION
**Pull request by mvarewyck**

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
@mvarewyck is this PR ready for review ?

**Comment by mvarewyck** [comment]
> @mvarewyck is this PR ready for review ?

Yes!

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@mvarewyck I know we didn't request it but can you also activate TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie for Damhert & Edelhert ?

**Comment by SanderDevisscher** [comment]
@mvarewyck which column do you use for type on FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke damherten per jaar? 
With damhert we get only onbekend while this should be Kalf (V), Smaldier, Hinde & Onbekend ? 

newplot (3)

**Comment by mvarewyck** [comment]
> @mvarewyck which column do you use for type on FIGUUR: Gerapporteerd aantal embryo's voor vrouwelijke damherten per jaar? With damhert we get only onbekend while this should be Kalf (V), Smaldier, Hinde & Onbekend ?
> 
> Same for Edelhert

Good point, we retain the female choices from column `type_comp` 'by hand' in the code. Currently (mistakenly) the ones from 'Wild zwijn' are taken.
So you want `c("Kalf (v)", "Smaldier", "Hinde", "Onbekend")` choices for both 'Damhert' and 'Edelhert'?

```
> table(droplevels(ecoData$type_comp[ecoData$wildsoort == "Damhert"]))

Kalf (v) Kalf (m) Smaldier  Spitser    Hinde     Hert Onbekend 
      65       78      126      148      161      188       19 
> table(droplevels(ecoData$type_comp[ecoData$wildsoort == "Edelhert"]))

Kalf (v) Kalf (m) Smaldier  Spitser    Hinde     Hert Onbekend 
      17        8        7       18       11       20        4 
```

**Comment by SanderDevisscher** [comment]
Yes

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
TABEL: Gerapporteerd afschot per regio en per leeftijdscategorie displays object 'levelsCategorie' not found instead of a table for damhert & edelhert

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@jimcasaer this PR adds the long requested graphs for edelhert & damhert but in the lab we determine the age in 4 categories (+Jaarling) compared to the 3 on the meldingsformulier. Am I correct to state Jaarling should be seen as Jongvolwassen in FIGUUR: Leeftijdscategorie op basis van onderkaak & meldingsformulier for damhert & edelhert? Current form:
newplot (4)

**Comment by jimcasaer** [comment]
I guess so yes, maybe best to check (to be 200% sure) with @LynnPallemaerts @emiliegelaude

**Comment by mvarewyck** [comment]
@SanderDevisscher while comparing the table for WBE with the one for grofwild I saw that we didn't include a row for 'Onbekend'. Is it fine if I add a row like below? I think this is better when users compare Total numbers with the graph above in the app.

Screenshot from 2024-04-18 11-27-36

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher while comparing the table for WBE with the one for grofwild I saw that we didn't include a row for 'Onbekend'. Is it fine if I add a row like below? I think this is better when users compare Total numbers with the graph above in the app.
> 
> Screenshot from 2024-04-18 11-27-36

Yes its fine

**Review by SanderDevisscher — APPROVED** [review]

**Comment by SanderDevisscher** [comment]
Everything seems to work like it should

**Pull request merged**
