### PR TITLE
fix #431 - projection sf version >1.0.0

### LINKED ISSUE #431: Vervormde leafletkaartjes
In de dev-versie van de faunabeheer website zijn de leafletkaartjes momenteel vervormd (uitgerokken en in bij wildschade ligt Vlaanderen in Frankrijk)

### PR DESCRIPTION
**Pull request by mvarewyck**
Fix for createShapeData() with sf version >= 1.0.0

### CODE REVIEW

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
I'm unable to build the app in docker. I get the following error:

```
#22 4.282 Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
#22 4.282   namespace ‘sf’ 0.9-8 is being loaded, but >= 1.0.0 is required
#22 4.282 Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
#22 4.282 Execution halted
#22 4.282 ERROR: lazy loading failed for package ‘reportingGrofwild’
```

**Comment by mvarewyck** [comment]
I checked `sf::sf_use_s2(FALSE)` also works for sf <= 1.0.0, so removed the restriction in DESCRIPTION.
Dockerfile build works again.

**Comment by SanderDevisscher** [comment]
@mvarewyck I've uploaded the spatialdata with `createShapeData()` again. But after succesfully building the app the issue persists. 

Also I think something else might be going on. Because when I look at the private page, these spatial files seem to work just fine. So between spatialDataWBE_sf.RData & the seperate wbe files might lay the solution. 

image

**Comment by mvarewyck** [comment]
> So between spatialDataWBE_sf.RData & the seperate wbe files might lay the solution.
I don't think so.
 
The maps on the public page (using spatialData_sf.RData) do NOT look fine, while the ones on the private page (using either spatialDataWBE_sf.RData for 'admin' or the seperate wbe files) do look fine. 
So, the problem is in spatialData_sf.RData. These shape files are indeed handled differently wrt projection: https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/master/reporting-grofwild/R/data_create.R#L56-L61
I just checked and this step is needed, given the provinces.geojson input file. 

I tried to mimick the creation of shape data as you do, and it seems to work

```
> packageVersion("sf")
[1] ‘1.0.14’
## My local version writes only to 'spatialData_mv.RData'
> createShapeData()
Spherical geometry (s2) switched off
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is FALSE
although coordinates are longitude/latitude, st_union assumes that they are
planar
[1] TRUE
> readS3(file = "spatialData_mv.RData")
> leaflet(spatialData$provinces) %>% addTiles() %>% addPolygons()
> sf_use_s2()
[1] FALSE
```

@SanderDevisscher Do you also get this notification `sf_use_s2() is FALSE` ? You only get it once, ie. the first time you run `createShapeData()` in a fresh R session. Later, you can ask for it using `sf_use_s2()`

**Comment by SanderDevisscher** [comment]
@mvarewyck at the start of createShapeData() I get the following notification:

```
Spherical geometry (s2) switched off
Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is FALSE
```

and this notification at the end:
```
although coordinates are longitude/latitude, st_union assumes that they are planar
Warning message:
package ‘sf’ was built under R version 4.3.1 
```

and running `sf_use_s2()` after the execution yields:
`[1] FALSE`

**Comment by mvarewyck** [comment]
I don't see why it's going wrong then.

Can you test this?

```
packageVersion("sf")
## [1] ‘1.0.14’
jsonDir <- "~/git/reporting-rshiny-grofwildjacht/data"
iLevel <- "provinces"
sf::sf_use_s2(FALSE)
file <- file.path(jsonDir, paste0(iLevel, ".geojson"))
shapeData <- geojsonsf::geojson_sf(file)
## This should give an ugly plot
library(leaflet)
leaflet(shapeData) %>% addTiles %>% addPolygons()
## This should give nice plot
suppressWarnings(sf::st_crs(shapeData) <- 31370)
shapeData <- sf::st_transform(shapeData, crs = "+proj=longlat +datum=WGS84")
leaflet(shapeData) %>% addTiles %>% addPolygons()
```

I can replace the `spatialData_sf.RData` for now if it's urgent.

**Comment by SanderDevisscher** [comment]
> I don't see why it's going wrong then.
> 
> Can you test this?
> 
> ```
> packageVersion("sf")
> ## [1] ‘1.0.14’
> jsonDir <- "~/git/reporting-rshiny-grofwildjacht/data"
had to change this to "~/github/reporting-rshiny-grofwildjacht/data"
> ```
> iLevel <- "provinces"
> sf::sf_use_s2(FALSE)
> file <- file.path(jsonDir, paste0(iLevel, ".geojson"))
> shapeData <- geojsonsf::geojson_sf(file)
> ## This should give an ugly plot
> library(leaflet)
> leaflet(shapeData) %>% addTiles %>% addPolygons()
Ugly indeed
image

>```
> ## This should give nice plot
> suppressWarnings(sf::st_crs(shapeData) <- 31370)
> shapeData <- sf::st_transform(shapeData, crs = "+proj=longlat +datum=WGS84")
> leaflet(shapeData) %>% addTiles %>% addPolygons()
> ```
Like it should be
image

> 
> I can replace the `spatialData_sf.RData` for now if it's urgent.

Can you include this file?
[Jachtter_2023-2024_dis.zip](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/13167076/Jachtter_2023-2024_dis.zip)

I'll disable the spatialData update for now to prevent accidental overwriting.

**Comment by SanderDevisscher** [comment]
maybe its a difference between linux & windows. I'll try to run createShapeData() in a docker container.

**Comment by SanderDevisscher** [comment]
I'll try this command
```
docker run --name test -p 4000:3838 inbo/grofwild R -e "Sys.setenv('AWS_DEFAULT_REGION'='eu-west-1', 'AWS_ACCESS_KEY_ID'='AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'='AWS_SECRET_ACCESS_KEY');reportingGrofwild::createShapeData(jsonDir = 'C:\\Users\\SANDER~1\\AppData\\Local\\Temp\\RtmpkDqYQn\\spatialData\\')"

**Comment by SanderDevisscher** [comment]
vermoedelijk doe ik nog iets mis maar ik krijg deze error als ik het via docker probeer:
```
Error in rcpp_geojson_to_sf(geojson, expand_geometries) : Invalid JSON
Calls: <Anonymous> ... geojson_to_sf -> geojson_to_sf.character -> rcpp_geojson_to_sf
Execution halted
```

**Comment by mvarewyck** [comment]
I think you need to specify a docker volume, to point your local files to some folder that's accessible within docker. I don't know how the slashes work in Windows :(

> I'll try this command
> 
> ```
> docker run --name test -v C:\\Users\\SANDER~1\\AppData\\Local\\Temp\\RtmpkDqYQn\\spatialData\\:\\jsonDir-p 4000:3838 inbo/grofwild R -e "Sys.setenv('AWS_DEFAULT_REGION'='eu-west-1', 'AWS_ACCESS_KEY_ID'='AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'='AWS_SECRET_ACCESS_KEY');reportingGrofwild::createShapeData(jsonDir = '/jsonDir')"
> ```

**Comment by SanderDevisscher** [comment]
using docker cp I was able copy the files to "/jsonDir". 
rerunning the container after yields the same result

**Comment by mvarewyck** [comment]
> Would be nice but not sustainable! This needs a fix.
> Can you include this file?
> [Jachtter_2023-2024_dis.zip](https://github.com/inbo/reporting-rshiny-grofwildjacht/files/13167076/Jachtter_2023-2024_dis.zip)

Is it fine if I just overwrite the spatialData_sf.RData?
Or does the shape data on the private app also needs an update? I don't have Jachtter_2022-2023

**Comment by SanderDevisscher** [comment]
apparently I was reading from an empty folder. For https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/435#issuecomment-1779532267 I used `;reportingGrofwild::createShapeData(jsonDir = '\\jsonDir')"` while for the `list.files()` which worked I used `;list.files('/jsonDir')"` 

I've changed the command to 
```
docker run --name test -p 4000:3838 inbo/grofwild R -e "Sys.setenv('AWS_DEFAULT_REGION'='eu-west-1', 'AWS_ACCESS_KEY_ID'='AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'='AWS_SECRET_ACCESS_KEY');reportingGrofwild::createShapeData(jsonDir = '/jsonDir')"
```

now I get this error:
```
Error in st_area.sfc(st_geometry(x), ...) : 
package lwgeom required, please install it first
Calls: <Anonymous> ... <Anonymous> -> st_area.sf -> st_area -> st_area.sfc
Execution halted
```
My local lwgeom version:
```
packageVersion("lwgeom")
[1] ‘0.2.13’
```

**Comment by mvarewyck** [comment]
> now I get this error:
> 
> ```
> Error in st_area.sfc(st_geometry(x), ...) : 
> package lwgeom required, please install it first
> Calls: <Anonymous> ... <Anonymous> -> st_area.sf -> st_area -> st_area.sfc
> Execution halted
> ```

Getting closer. I pushed a new dockerfile which should fix this issue.

**Comment by mvarewyck** [comment]
> `createShapeData()` completed without throwing an error in docker but it seems the error persists :-(

I can now reproduce in docker with 'sf' version > 1.0.0

**Comment by SanderDevisscher** [comment]
> > `createShapeData()` completed without throwing an error in docker but it seems the error persists :-(
> 
> I can now reproduce in docker with 'sf' version > 1.0.0

The error you mean ? ifso jippie ??

**Comment by mvarewyck** [comment]
> > > `createShapeData()` completed without throwing an error in docker but it seems the error persists :-(
> > 
> > 
> > I can now reproduce in docker with 'sf' version > 1.0.0
> 
> The error you mean ? ifso jippie ??

No, it was because there was still a `geojson.zip` file in my folder. Creating the shape data with docker works correctly for me (even with `--no-cache` and using the latest sf). All data is now up to date on UAT.

**Comment by SanderDevisscher** [comment]
damn

**Comment by mvarewyck** [comment]
@SanderDevisscher Can you test your script again? It works for me, but I still have the old geojson files for the provinces etc.

**Review by SanderDevisscher — APPROVED** [review]
Issue has been fixed

**Comment by SanderDevisscher** [comment]
@mvarewyck can you resolve the last remaining conflict?

**Comment by mvarewyck** [comment]
@SanderDevisscher Docker builds and runs fine for me now.

**Review by SanderDevisscher — APPROVED** [review]
Builds in docker like a charm

**Pull request merged**
