### PR TITLE
218 test wbe

### PR DESCRIPTION
**Pull request by mvarewyck**
Include all code for the WBE page in the R package.

NOTE: The WBE page is still invisible from the main grofwild app:
https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/218_test_wbe/reporting-grofwild/inst/ui/app_public/ui.R#L49

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
I'll build the public & non-public app in docker as a test. 
When there are no breaking issues I'll approve this PR. 

@jimcasaer this PR contains some changes to the main grofwild app as well. Do you think it opportune to use this occasion to publish the new wildschade data ?  Or should we wait for other issues at our side to be resolved ?

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
While testing the **wbe page** in docker the following issues occurred that should be fixed best before approving the PR:

- [ ] the app timed out when selecting aantal/100ha bos & natuur
- [ ] "FIGUUR: Afschot per jachtmethode" is missing for wild zwijn, edelhert & damhert

for the rest the issues are not "breaking"

- [ ] the display of n overlaps for several graphs, example:

image

**Comment by mvarewyck** [comment]
We will turn the labels 90 degrees when more than 10 boxes are shown.

Screenshot from 2022-04-04 08-38-59

**Comment by jimcasaer** [comment]
seizoenen mogen vervangen worden door per kwartaal (31/3 / 31/6/31/9 / 31/12) @mvarewyck

**Comment by mvarewyck** [comment]
> seizoenen mogen vervangen worden door per kwartaal (31/3 / 31/6/31/9 / 31/12) @mvarewyck

Is dat dan 'Kwartaal 1', 'Kwartaal 2' enz. of eerder 'Jan, Feb, Maart' enz. in de figuur (hover text) ?

**Comment by mvarewyck** [comment]
@SanderDevisscher Ready for merge from my side.

**Review by SanderDevisscher — APPROVED** [review]
Everything works as wanted.
Something to remember to improve however, decimal percentages, see #279. This 
should also be included in the wbe page

**Comment by SanderDevisscher** [comment]
@mvarewyck I'll maintain this branch ?

**Comment by mvarewyck** [comment]
I would suggest to keep this branch until we have the WBE online.

**Pull request merged**
