### PR TITLE
:construction_worker: Add deployment uat workflow

### LINKED ISSUE #491: Create automatic deployment action
- [ ] github action(s) Analog to alien species portal. `uat` (on merge) or any other branch (on PR) -> faunabeheer-dev.inbo.be & wbe-dev.inbo.be || `master`  branch (on merge) -> faunabeheer.inbo.be & wbe.inbo.be
- [ ] Make sure githash is also passed.

### LINKED ISSUE #492: Github action voor automatische deployment op nieuwe omgeving

### PR DESCRIPTION
**Pull request by TheJenne18**

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
I suppose it is best to wait for #489 to be finished ?

**Comment by TheJenne18** [comment]
Yes 👍

**Comment by SanderDevisscher** [comment]
@TheJenne18 what is the best course of action to test this PR ?

**Comment by SanderDevisscher** [comment]
@TheJenne18 what should I do to test this ?

**Comment by SanderDevisscher** [comment]
@TheJenne18 next steps ?

**Review by SanderDevisscher — APPROVED** [review]
Not tested by me !

**Pull request merged**
