### PR TITLE
fix #205 - squeezed plotly bars

### LINKED ISSUE #205: FIGUUR: Gerapporteerd aantal per jaar en per regio is compressed in docker env.
The error (see image below) occurs with both roedeer and wild boar.

image

### PR DESCRIPTION
**Pull request by mvarewyck**

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
initial issue with squeezed bars seems to be fixed

**Comment by mvarewyck** [comment]
> There is some small text above the bars of [FIGUUR: Verdeling afschot over de jaren](http://localhost:3800/#) image Its seems also occur on [FIGUUR: Verdeling afschot over de jaren](http://localhost:3800/#). These should be deleted.

This is an easy fix, though hard to detect in which plots it is introduced (by plotly 4.10.1). Let me know if you see it on other plots.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@mvarewyck currently the jaar - interval plot seems to be unsqueezed while in the case of the other intervals all but the last year appear squeezed, see below:

newplot

(FIGUUR: Verdeling afschot over de jaren kwartaal interval)

**Comment by mvarewyck** [comment]
> @mvarewyck currently the jaar - interval plot seems to be unsqueezed while in the case of the other intervals all but the last year appear squeezed, see below:
> 
> (FIGUUR: Verdeling afschot over de jaren kwartaal interval)

@SanderDevisscher This is a different issue. For this plot we combine multiple plots (one per year) in a grid. The first and last plot will always have a bit more space (different margins). I can have a look on how to optimize margins.

**Comment by SanderDevisscher** [comment]
would be nice if you can

**Comment by mvarewyck** [comment]
> would be nice if you can

I've set smaller margins for all subplots. 

newplot

**Review by SanderDevisscher — APPROVED** [review]

**Comment by SanderDevisscher** [comment]
The issues appear to be fixed in docker.

**Pull request merged**
