### PR TITLE
version 0.3.2

### PR DESCRIPTION
**Pull request by mvarewyck**

### CODE REVIEW

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
#426 seems to not be fixed by this PR. When I select verwilderde kat and switch the source (select the only source HVV_wilder) the app still times out.  
When looking at the docker logs I see this:
```
Warning: Error in mapply: zero-length inputs cannot be mixed with those of non-zero length
2023-11-27 15:31:18   70: mapply
2023-11-27 15:31:18   69: Map
2023-11-27 15:31:18   67: <reactive>
2023-11-27 15:31:18   51: results$textPopup
2023-11-27 15:31:18   45: <observer>
2023-11-27 15:31:18    2: runApp
2023-11-27 15:31:18    1: reportingGrofwild::runWildApp
```

#439 seems to be fixed on all levels and parts of the app

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
#442 seems to be fixed but when I select 1 dashboard indicator all other indicators get enabled as well

**Comment by SanderDevisscher** [comment]
eea675b39ee699b21673cba496e6cb68360d6bb1 implemented some fix but it seems to no longer do the trick.

**Comment by SanderDevisscher** [comment]
selecting a province, faunabeheerzone or gemeente enables all indicators as well.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
Some issues still occur with the dashboard:

When selecting only waarnemingen for huidige verspreiding everzwijn I get the following error: 

image

it is independent of year.
Selecting only afschot yields the same view. While selecting both yields the expected view.
Selecting neither results in a timeout. The timeout occurs also in PRD, the other issues not.

**Comment by mvarewyck** [comment]
**Note:** Commit [a8f6407](https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/440/commits/a8f640721e3f2052d5103737d45bdc7ddf0f86ee) requires the wildschade data to be created again (column `dataSource` replaces `indieningType`). 
I've replaced the data on S3 bucket "inbo-wbe-uat-data" (applied required changes to current data on S3 and uploaded to S3 again).

**Comment by SanderDevisscher** [comment]
ok for review ?

**Comment by mvarewyck** [comment]
> ok for review ?

@SanderDevisscher yes docker runs fine locally

**Review by SanderDevisscher — APPROVED** [review]
all issues appear to be fixed

**Pull request merged**
