### PR TITLE
Update august 2023

### PR DESCRIPTION
**Pull request by mvarewyck**

### CODE REVIEW

**Review by SanderDevisscher — COMMENTED** [review]
@mvarewyck possibly I use a wrong build command but when using the command below I get this git hash GIT: [$(git rev-parse HEAD)](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/$(git%20rev-parse%20HEAD))

I use this build command:
`'docker build --build-arg "GIT_SHA=$(git rev-parse HEAD)" -t inbo/grofwild .'`

**Comment by mvarewyck** [comment]
> @mvarewyck possibly I use a wrong build command but when using the command below I get this git hash GIT: [$(git rev-parse HEAD)](https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/$(git%20rev-parse%20HEAD))
> 
> I use this build command: `'docker build --build-arg "GIT_SHA=$(git rev-parse HEAD)" -t inbo/grofwild .'`

I use it without the inner-quotes:

`sudo docker build --build-arg GIT_SHA=$(git rev-parse HEAD) -t inbo/wildapp .`

**Comment by SanderDevisscher** [comment]
Ok I'll try

**Comment by mvarewyck** [comment]
In case it needs an update: it is documented [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/update_august_2023/README.md#troubleshooting)

**Review by SanderDevisscher — APPROVED** [review]
Dropping the inner qoutes and adding powershell to the system command fixed my build issue.

**Pull request merged**
