### PR TITLE
Feature#438

### PR DESCRIPTION
**Pull request by Yingjie-ZhangOA**
implementation of kencijfer tabel

### CODE REVIEW

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
When building the package locally using
```{r build new image}
setwd(dir = "../reporting-rshiny-grofwildjacht/")
system(command = 'powershell "docker build --build-arg GIT_SHA=$(git rev-parse HEAD) -t inbo/grofwild ."')
setwd("~/GitHub/backoffice-wild-analyse")
```
I get the following error:
```
#22 [18/19] RUN R -q -e "remotes::install_local('/tmp/package', dependencies=FALSE)"
#22 0.678 > remotes::install_local('/tmp/package', dependencies=FALSE)
#22 4.350 Running `R CMD build`...
#22 4.704 * checking for file ‘/tmp/RtmpLkK4QH/file7101b0448/package/DESCRIPTION’ ... OK
#22 4.704 * preparing ‘reportingGrofwild’:
#22 4.704 * checking DESCRIPTION meta-information ... OK
#22 4.704 * checking for LF line-endings in source and make files and shell scripts
#22 4.704 * checking for empty or unneeded directories
#22 4.704 * building ‘reportingGrofwild_0.3.1.tar.gz’
#22 4.706 Installing package into ‘/usr/local/lib/R/site-library’
#22 4.706 (as ‘lib’ is unspecified)
#22 4.992 * installing *source* package ‘reportingGrofwild’ ...
#22 4.992 ** using staged installation
#22 5.004 ** R
#22 5.039 Error in parse(outFile) : 
#22 5.039   /tmp/RtmpTmdCI7/R.INSTALL4135bf54f1/reportingGrofwild/R/tableKencijfers.R:62:116: unexpected '>'
#22 5.039 61:     
#22 5.039 62:     common <- intersect(dataCurrentYear[[ "gemeente_afschot_locatie"]],dataPreYear[["gemeente_afschot_locatie"]]) |>
#22 5.039                                                                                                                        ^
#22 5.039 ERROR: unable to collate and parse R files for package ‘reportingGrofwild’
#22 5.039 * removing ‘/usr/local/lib/R/site-library/reportingGrofwild’
#22 5.050 Warning message:
#22 5.050 In i.p(...) :
#22 5.050   installation of package ‘/tmp/RtmpLkK4QH/file77c27bf7e/reportingGrofwild_0.3.1.tar.gz’ had non-zero exit status
#22 5.050 > 
#22 5.050 > 
#22 DONE 5.1s
```

**Comment by Yingjie-ZhangOA** [comment]
issue cause by the new pipe operator "|>" is not available in R versions prior to R4.1.0,  removed the use of pipe.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
I'm able to build the app now.

Just 1 thing that should be fixed before merging, namely the thresholds reset when changing the year. Can these remain set until the user changes them ?

**Comment by Yingjie-ZhangOA** [comment]
> I'm able to build the app now.
> 
> Just 1 thing that should be fixed before merging, namely the thresholds reset when changing the year. Can these remain set until the user changes them ?

It's something we can do, but what if the retained threshold exceeds the range of the data given currently selected year. Should we extend the range to cover the retained threshold? it feels a bit weird as the range doesn't reflect the actual data.

**Comment by mvarewyck** [comment]
> It's something we can do, but what if the retained threshold exceeds the range of the data given currently selected year. Should we extend the range to cover the retained threshold? it feels a bit weird as the range doesn't reflect the actual data.

If the currently selected threshold exceeds the range I would reset it to the default starting value. Not extend the range.

**Comment by SanderDevisscher** [comment]
> > I'm able to build the app now.
> > Just 1 thing that should be fixed before merging, namely the thresholds reset when changing the year. Can these remain set until the user changes them ?
> 
> It's something we can do, but what if the retained threshold exceeds the range of the data given currently selected year. Should we extend the range to cover the retained threshold? it feels a bit weird as the range doesn't reflect the actual data.

Hmm, you make a valid point. However I think our users will mainly want to compare the situation 1 one year with another once they have set their preferred threshold. Also I think they'll mainly set "low" thresholds so this won't be that big an issue. However we need to anticipate some users that will exceed the data range threshold. 
I think therefor it is best to set a disclaimer when the threshold exceeds the data range stating something like: "De gekozen drempelwaarde is ligt hoger dan de beschikbare data voor dit jaar, verlaag de drempelwaarde!"

**Comment by SanderDevisscher** [comment]
> > It's something we can do, but what if the retained threshold exceeds the range of the data given currently selected year. Should we extend the range to cover the retained threshold? it feels a bit weird as the range doesn't reflect the actual data.
> 
> If the currently selected threshold exceeds the range I would reset it to the default starting value. Not extend the range.

Even better ;-)

**Comment by Yingjie-ZhangOA** [comment]
> > > It's something we can do, but what if the retained threshold exceeds the range of the data given currently selected year. Should we extend the range to cover the retained threshold? it feels a bit weird as the range doesn't reflect the actual data.
> > 
> > 
> > If the currently selected threshold exceeds the range I would reset it to the default starting value. Not extend the range.
> 
> Even better ;-)

In case of retained selection exceeds the range,  the maximal value is taken as default  fc8e843

**Comment by SanderDevisscher** [comment]
@Yingjie-ZhangOA were all necessary changes been implemented ?

**Comment by Yingjie-ZhangOA** [comment]
> @Yingjie-ZhangOA have all necessary changes been implemented ?

Yes 

> In case of retained selection exceeds the range, the maximal value is taken as default. 

This has been implemented in https://github.com/inbo/reporting-rshiny-grofwildjacht/commit/fc8e843797ef22ae09e023bcd2068f19eb59bd9c

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
The kencijfer tabel is now as it should be, however something has gone wrong with the selection of the other graphs/tables/maps. When I for example switch directly to the province Limburg all graphs, maps & tables seem to be selected while none actually are.  

Selecting "tabel Kencijfers" seems to reset the issue showing only the selected item, afterwards.

**Review by SanderDevisscher — APPROVED** [review]
the pending issue concerning all dashboard options being activated seems to be fixed. However when I looked at the downloadable data for 2013 I noticed waarnemingen to be missing.

Here are some suggestions for further enhancement:
- [ ] add the column to the download even if the data is not available. In this case all values should be NA. 
- [ ] rename "waarnemingen.be" to just "waarnemingen"

and for the sake of consistency:

- [ ] rename "category" to "categorie"
- [ ] rename "counts" to "aantal"
- [ ] rename "municipality" to "gemeente"

**Pull request merged**
